### ISSUE TITLE
Posted in Blog/News links

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#106]
I don't think that the links to 'posted in blog' ( or news or the tags) on blog posts are necessarily useful with the way we have set up the site - i.e there are no direct links to blog, and the News category is News&Updates.

I'd propose removing them completely (but we should consider if tags are useful before we do this)

**Comment by morchickit** [comment]
@caprenter - I think this is obsolete if we want to change the blog layout. Can I close it?

**Comment by caprenter** [comment]
Sure.
