### ISSUE TITLE
Template for custom fields / call to actions

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/website#11]
At the moment the custom fields for a horizontal bar of calls to action can only be used on the front page.

It would be useful to have a template set-up that allows these to also be used on pages such as the 'Get Involved' page.

**Comment by caprenter** [comment]
I think we need to make these specifically for each page - it depends on how many of these banners each one requires and how many 'call to action' buttons it needs and so on.

I can set one up for the Get Involved page.

**Comment by caprenter** [comment]
Get involved page is set up now. Closing this, but re-open if more are needed
