### ISSUE TITLE
Failure to get data from salesforce

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#114]
We were notified of missing data from the data registry page https://www.threesixtygiving.org/data/data-registry/ by a monitoring service.

Investigation tells us:

That the use of transients is problematic.
From https://codex.wordpress.org/Transients_API : Transients may expire before the $expiration (Due to External Object Caches, or database upgrades) but will never return their value past $expiration.

When we check the transient:https://github.com/ThreeSixtyGiving/website/blob/master/wp-content/plugins/threesixty_salesforce_data/threesixty_saleseforce_data.php#L13
if it has expired we cannot retrieve the data it contains (the dcat.json from endpoint: http://data.threesixtygiving.org/data.json )

..so we try to get it again.
Currently if it fails it will write the error message to the transient instead:
e.g. O:8:"WP_Error":2:{s:6:"errors";a:1:{s:19:"http_request_failed";a:1:{i:0;s:80:"cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received";}}s:10:"error_data";a:0:{}}

However when we go to the page, the transient is now set, but with useless data. As the expiration is set for an hour, the page will remain in that state until another visitor comes along. If that is over an hour later a refresh will be triggered.

We could:
1) test that we do get a proper response on wp_remote_get: https://codex.wordpress.org/Function_Reference/wp_remote_get  - and not set the transient. This would give people a chance with a page reload.
We could accompany that with a message to say to try again later.

2) Rewrite this so that a cached copy can always be served

3) other

**Comment by caprenter** [comment]
NB the website can be made to work again by removing the transients from the database:

_transient_dcat-json-data
_transient_timeout_dcat-json-data

**Comment by morchickit** [comment]
@caprenter  - is this going to affect our current efforts on the website?

**Comment by caprenter** [comment]
I don't think so - but this is an example of the risk we carry until we find a better way of doing the registry
