### ISSUE TITLE
Terms mentions copyright notice that does not exist

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#118]
http://www.threesixtygiving.org/terms-conditions/
"This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions."

I don't see a copyright notice

**Comment by drkane** [comment]
Copyright notice now in footer
