### ISSUE TITLE
Top navigation bar changes

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/website#12]
- [x] Remove 'Home' from the top navigation bar, and just make 360Giving link a click target for home;
- [x] The original design has a light drop shadow on the top navigation bar;
- [ ] Top navigation bar should stay attached to the top of the screen on scroll;
- [ ] Top navigation bar needs to work with responsive design (currently gets lost under search box)

**Comment by caprenter** [comment]
Two out of four addressed. Moving the remaining issues to #23 and #24
