### ISSUE TITLE
Updating links to CoVE

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#122]
Related to https://github.com/ThreeSixtyGiving/standard/issues/181

In the wordpress content, have we any links to Cove?

If so, please can we edit them to point at https://dataquality.threesixtygiving.org/

cc/ @KDuerden

**Comment by caprenter** [comment]
I've updated the following pages on the live site:
https://www.threesixtygiving.org/take-down-policy/
https://www.threesixtygiving.org/manchester/
https://www.threesixtygiving.org/data/publish-data/
https://www.threesixtygiving.org/data/data-quality/
