### ISSUE TITLE
Connect Medium account to our wordpress

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/website#128]
For that we will need:

- [x] Create 360Giving Medium account - https://medium.com/@360Giving

- [ ] Install plug in - see https://help.medium.com/hc/en-us/articles/213510158-Medium-WordPress-plugin

- [ ] Test that it's working!

@caprenter - I think I can do it alone, but I am tagging you here in case things will get messy :-) 
Should I do the plug in on the staging or the live site?

**Comment by caprenter** [comment]
Let me do fetch and install the plugin - again as part of the current development workflow we do this via a local instance, push a copy to github, then use git to deploy to staging (and later production).

So lets keep with that until we untangle the docs, and then we can move to the more standard wordpress way of things.

**Comment by caprenter** [comment]
@morchickit - the medium plugin is now active on the staging site. It's brought into this repo via the commit above, so we could deploy to live if we wanted to.

I've created a new branch 'development-july-17' to do the current work on.
