### ISSUE TITLE
Make sure all of the links on the site are pointing to the new documentation 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/website#129]
To be done when @stevieflow is giving us a go!

**Comment by stevieflow** [comment]
Linked to https://github.com/ThreeSixtyGiving/standard/issues/203

**Comment by stevieflow** [comment]
So - http://standard.threesixtygiving.org can be used as the link to point to the documentation, in terms of any links manually curated in Wordpress

**Comment by stevieflow** [comment]
Closing.  Reopen if otherwise
