### ISSUE TITLE
Documentation page template: left-margin & hiding left-hand menu

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/website#13]
For narrower page widths, the text of the documentation page gets lost behind the left-hand navigation.

For very narrow page widths, the left-hand navigation menu should be hidden or turned into a responsive drop-down sub-menu.

**Comment by caprenter** [comment]
I've not been able to find a fix for this yet. And I'm a bit stumped

**Comment by caprenter** [comment]
I think this is done

**Comment by caprenter** [comment]
Closing this as done. Any bugs can be reported as such
