### ISSUE TITLE
Setup forwarding of WP documentation links to new documentation URL?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#133]
To look at whether certain paths in WP documentation can auto forward to new documentation links - eg:

http://www.threesixtygiving.org/standard/reference/ --> http://standard.threesixtygiving.org/en/latest/reference/

http://www.threesixtygiving.org/standard/identifiers/ --> http://standard.threesixtygiving.org/en/latest/identifiers/

etc

However, we may choose at a later date to rearrange some of the navigation and pages.  Therefore, it might be prudent to just redirect all under http://www.threesixtygiving.org/standard/ to http://standard.threesixtygiving.org/en/latest/

Assigned to a few people to implement - but initial question/decision is with @KDuerden

**Comment by KDuerden** [comment]
My preference is for re-direct for key pages (reference, identifiers, open licensing) at the point of change over.

We want the rearrangement of the navigation/pages to help users find what they need/improve the signposting to resources. Once this is done I expect the redirect will be less necessary, but it would be useful to have in the interim.

**Comment by caprenter** [comment]
Redirects can be set up in the wp-engine dashboard - so the task is not that difficult. 

We will need a comprehensive list of current links and where they should be redirected to in order to get this done. Steven has started some suggestions, but this ticket is a good place to have the definitive list.

**Comment by stevieflow** [comment]
@KDuerden Ive started a sheet to log and sign off the redirects:

https://docs.google.com/spreadsheets/d/1wKEYXXtVazvlCL_yYr6pGakFtOMTsMYVSKo5IwQIk4U/edit#gid=0

Do you think you can add any more?  Thanks

**Comment by stevieflow** [comment]
I think this is done.  Closing
