### ISSUE TITLE
Pages text does not show if they are not styled 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/website#139]
Normal paragraph text does not show in the theme when it's publish (it looks invisiable). Text is shown only after being styled  (bold, italic or a header) publishing, and then changing the style to paragaph again...

**Comment by caprenter** [comment]
That sounds a bit odd.

Can you give me steps to try to reproduce?
Are you typing in text or pasting it from elsewhere? (If pasting what application does it get pasted from?)

**Comment by morchickit** [comment]
I pasted it from Google docs to the CMS. It was formatted in the Google
Doc, and in the CMS, but when hiring the publish button the normal text
disappear.
I had to make the whole text in bold and then hit publish again to make the
text to show. Then I had to reformat back to normal text.
Katherine says it happens both on pages and post pages.

Any more information I can give here to look at this?

**Comment by caprenter** [comment]
So this is do do with copy and pasting from (elsewhere) into the wordpress editor.

My advice is always to copy plain text into wordpress and do the formatting there - don't try to carry formatting and links etc over.

There are many articles about how to work around these copy and paste issues from (Word|GoogleDocs|Other) e.g. https://kinsta.com/blog/google-docs-to-wordpress/

I would use google docs to write (and spellcheck!) then past directly into the 'Text' tab of the wordpress editor. Then select the 'Visual' editor and format from there.
