### ISSUE TITLE
Support for full-width header images

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/website#14]
The original design includes a featured image styled page.

If a page or blog post has a featured image set, this should be displayed, centered, full width within a bar of up to 300px (might need to tweak this height... use something relative for better responsive design). 

There might be plugins that can help with ensuring this is done in the best way for different screen sizes, in terms even of serving up appropriate sized image. 

(Lower priority)

**Comment by caprenter** [comment]
I've had a play this and it's a little problematic. Aligning the image with the top of the page and negotiating the search bar is difficult.

The design has the writing/page title on the image - in my experience this can mean it is often illegible depending on the image.

To place the writing on the image would require some conditional css for when the image is not there as well.

**Comment by ekoner** [comment]
This looks like it is no longer needed as we've had a site redesign. @caprenter please confirm
