### ISSUE TITLE
Remove reference to documentation generation / plugin?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#140]
The README still contains reference to this plugin.  To remove? 

There's also https://github.com/ThreeSixtyGiving/website/tree/master/wp-content/plugins/threesixty_docs - should this be removed also?

**Comment by caprenter** [comment]
The site still works with that plugin as part of the set up. But we don't really need it.

The README does need an update - but it's a fairly significant update because it needs a full re-write really.

I'll do it in the next week or so

**Comment by stevieflow** [comment]
I did a very quick thing on the README - I moved the section on the docs to the end

**Comment by caprenter** [comment]
On reflection - there's not much point in maintaining any of this. As new developers take the site and administer it their way, it's probably worth leaving this as a document about how we used to do things. 
The info on the 'find data' page for example is still useful, but the rest can be passed over
