### ISSUE TITLE
"It currently includes:" counter animation doesn't activate

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/website#141]
The new threesixtygiving.org has a cool counter on it, but some of us are blessed with large monitors (or browser windows) which mean we don't need to scroll! This means the event doesn't fire and it stays at 0.

I'd check that the element isn't already in view first and then if it isn't bind to the scroll event otherwise call .start straight away.
https://github.com/ThreeSixtyGiving/website/blob/d852673a0f25e9324f193ce21edb7896ae998af1/wp-content/themes/360giving/assets/js/script.js#L75 ?

**Comment by drkane** [comment]
Good point, thanks.

There's a new version of the website coming soon ([sneak peek of very early stage prototype](http://stag360giving.wpengine.com/)) which won't have fancy counters on the numbers, so this issue won't apply.

**Comment by drkane** [comment]
Counter has now gone, thereby fixing this issue...
