### ISSUE TITLE
Discrepancies in values

### ISSUE THREAD

**Issue by notshi** [ThreeSixtyGiving/website#142]
![Screenshot-20200326150405-1069x353](https://user-images.githubusercontent.com/1515961/77662013-3c312f80-6f73-11ea-9bb4-209d25ab2bbf.png)
Might be a cache problem, or it's currently being fixed but it looks like the funders list is empty on the main site (as of 26 Mar, 15:07:46).

There also seems to be a discrepancy in the number of grants; ie. compared to grantnav.
![Screenshot-20200326150640-1006x165](https://user-images.githubusercontent.com/1515961/77662226-7ef30780-6f73-11ea-87a8-c1d84ff103c0.png)

**Comment by drkane** [comment]
Apologies @notshi  - only just seen this issue, many thanks for raising it.

The caching issue is now fixed, but the discrepancy remains. I need to change the reference https://github.com/ThreeSixtyGiving/website/blob/f042e4b1cebfc8b5816e1fcf59c8cec5b475bd52/wp-content/themes/360giving2020/functions/get-numbers.php#L5 to `http://store.data.threesixtygiving.org/reports/latest_status.json` to be consistent with GrantNav.

**Comment by notshi** [comment]
No worries @drkane wasn't sure where to raise this as the last open issue was 3 years old so thanks for the update!

**Comment by drkane** [comment]
Now fixed
