### ISSUE TITLE
Side-bar less fixed-width template

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/website#15]
I couldn't find a template to use for pages such as 'About' which didn't have sidebars, but kept to the narrower page width. Is there one available? 

If not - we'll need to have one - possibly making that the default template for newly created page. 

Linked to #11

**Comment by caprenter** [comment]
Have removed sidebars on pages like this, but not sure if it is exactly what you are after

**Comment by timgdavies** [comment]
Yep - that's looking good.

**Comment by caprenter** [comment]
I think this is ok to close
