### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#18]
The website doesn't have any T&C's

**Comment by stevieflow** [comment]
Flagging with 360 / blocked

**Comment by caprenter** [comment]
There is also a disclosure policy that may need to be added

**Comment by caprenter** [comment]
These are now in staging: http://opendataservic.staging.wpengine.com/terms-conditions/

**Comment by caprenter** [comment]
These are now on live
