### ISSUE TITLE
Cookie Policy

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#19]
There is no cookie policy or opt-in/out process

**Comment by stevieflow** [comment]
Flagging with 360 / blocked

**Comment by caprenter** [comment]
We should probably just install https://wordpress.org/plugins/uk-cookie-consent/

**Comment by stevieflow** [comment]
ok, please

**Comment by caprenter** [comment]
This is being deployed right now to http://opendataservic.staging.wpengine.com/
@stevieflow Please try it out.

**Comment by stevieflow** [comment]
@caprenter tested / check and looks good.

**Comment by caprenter** [comment]
This was done in #70
