### ISSUE TITLE
Connect to Wordpress.com

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#2]
Some plugins require a connection to wordpress.com - we need to set this up for the appropriate user

**Comment by caprenter** [comment]
@timgdavies Did you find me an account to make this connection? I think we decided not to use our personal ones, and that someone at 360 should own it.

**Comment by stevieflow** [comment]
I can do this , I think

**Comment by caprenter** [comment]
Did you ever get anywhere with this @stevieflow?

**Comment by stevieflow** [comment]
Yes - it's connected via an email @threesixtygiving.org
