### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#20]
I think wordpress has some in built dashboard stats - is this sufficient?

**Comment by caprenter** [comment]
(we should check these are enabled - probably requires connection to wordpress.com #2 )

**Comment by stevieflow** [comment]
@caprenter this seems to rest on Jetpack (https://jetpack.me/) which is a) requiring an update and b) needs some kind of connection (possibly by a user - #2 )....

**Comment by timgdavies** [comment]
Couldn't we use our Piwiki install and the wordpress plugin for that?

**Comment by caprenter** [comment]
We could. Options are wordpress - anyone that accesses the admin part of the site has access
Google/Piwik - need access to those accounts etc.

What's the requirement?

**Comment by stevieflow** [comment]
The original note said:

> I think wordpress has some in built dashboard stats - is this sufficient?

When I log-in, I cannot see any of these - possibly because JetPack is not connected.

It would be useful to get this going first of all - but I think that then relies on https://github.com/ThreeSixtyGiving/website/issues/2, which I've assigned to myself

**Comment by caprenter** [comment]
We have site stats working now within wordpress. I think that is sufficient. Closing this.
