### ISSUE TITLE
Disable comments on posts/pages 

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#27]
Many pages have comments enabled. We could disable them sitewide, or on each page as we see fit.

**Comment by caprenter** [comment]
This is probably just a final check

**Comment by stevieflow** [comment]
I've removed comment function from Pages, but not 100% sure we need to do so for Posts - @timgdavies any opinion?

**Comment by timgdavies** [comment]
I personally think it is useful to keep comments option on blog posts - but something to check with Rachel Rank for final decision.

**Comment by stevieflow** [comment]
Have checked with RR and have now enabled comments on blog posts, with moderation
