### ISSUE TITLE
Smooth scroll needs to stop further down page

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#30]
On e.g. http://opendataservic.wpengine.com/standard/publish/#toc2

Now the navs are fixed, the scroll goes too far up the page.

I think the answer is in overiding the smooth scroll options, but not sure how to do it.
Our JS is in the footer, and these are useful documents:
https://github.com/kswedberg/jquery-smooth-scroll
https://github.com/jgallen23/toc/blob/master/lib/toc.js

**Comment by timgdavies** [comment]
Adding the following CSS should fix this:

```
.post-entry span {
  height: 100px;
  margin-top: -100px;
  display: block;
  visibility: hidden;
}
```

**Comment by caprenter** [comment]
Works for me

**Comment by caprenter** [comment]
Thanks
