### ISSUE TITLE
'About' is in the #toc navigation 

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#31]
On e.g. http://opendataservic.staging.wpengine.com/standard/reference/

About appears at the bottom of the left hand 'toc' navigation. This is because the javascript is picking up that heading in the footer and using it.

The javascript could do with a fix. I'm not sure on how to do that.

**Comment by timgdavies** [comment]
An untested update in the standard repository - which looks for a heading called About, and removes text if found...

Can you push to staging so I can see if this does the job?

**Comment by timgdavies** [comment]
Looks like my tweak didn't work - but just removing the 'About' heading from the widget works for now.
