### ISSUE TITLE
Create Blog posts

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#32]
Currently we only have demo blog posts. These should be removed.

Are we simply copying over the old posts to the new site?

**Comment by timgdavies** [comment]
Yes - Will has asked for existing blog posts to be copied over. 

Is this something you can cover?

**Comment by caprenter** [comment]
Sure

**Comment by caprenter** [comment]
I think this is now done

**Comment by stevieflow** [comment]
These are in the site
