### ISSUE TITLE
Centering and layout of logos needs work

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#33]
E.g. Nominet Trust logo should be vertically centred in the grid square it is in

**Comment by caprenter** [comment]
My thoughts on this are that the problems with the logos are at the source.

I've chosen to display what ever logo I can pull from the dkan at a height and width of 150px.

I _think_ the way to deal with this is to fix the images at source - but there may be a better way.

I'm not sure of one tho, so I don't have any plans to fix this

**Comment by timgdavies** [comment]
I don't see why when images are not 150px high we can't centre them within the grid square they are in. 

What would a fix at source for e.g. the Nominet Trust logo look like?

**Comment by caprenter** [comment]
Sorry, I gave a bit of false info above. 

The html on the images sets width:150 height:150 but there is css that sets height to 'auto'

so Nominet trust is uploaded at DKAN at 222x31, we pull that and store a copy, and then display an image that is 150x21

I can't seem to find the css to centre this logo in the square allocated on the front page.

In terms of these logos tho, I think Nominet trust is the least of the problems. (see Welcome trust, True Colours, Staples, etc)

I also thought that Part of the task for this was possibly to be selecting logos.

So I think there is a task to be done about curating the logos at the DKAN source, and maybe creating a white/black list on this new site.

**Comment by caprenter** [comment]
Logos that should not be there are taken off now

**Comment by caprenter** [comment]
This has been working on the live site for months now. There are still issues with how the logos look IMHO, so I'll keep this open, but move from the go live milestone

**Comment by stevieflow** [comment]
I think we can close this and detail any specific on logo layout during/after the shift to Salesforce?

Reopen if otherwise
