### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#35]
We could run a check for broken links

**Comment by caprenter** [comment]
Linkchecker reports:
- [x] http://threesixtygiving.com/grant-data/data-standard/ - http://www.threesixtygiving.org/blog/
- [x] http://threesixtygiving.com/grant-data/ - http://www.threesixtygiving.org/blog/
- [x] http://threesixtygiving.com/data-standard/ - http://www.threesixtygiving.org/blog/
- [x] http://threesixtygiving.com/2013/06/24/five-year-ambition-for-open-philanthropy-in-the-uk/ - http://www.threesixtygiving.org/blog/
- [x] http://threesixtygiving.com/2013/10/24/big-lottery-fund-leads-the-way-to-transparency-in-grant-making-with-colossal-data-release/ - http://www.threesixtygiving.org/blog/
- [x]  /2013/06/24/five-year-ambition-for-open-philanthropy-in-the-uk/ - http://www.threesixtygiving.org/blog/page/2/
- [x] http://www.threesixtygiving.org/wp-content/uploads/2013/06/esmee-map.jpg   - http://www.threesixtygiving.org/blog/page/2/
- [x] http://www.threesixtygiving.org/wp-content/uploads/2013/06/esmee-map-150x150.jpg   - http://www.threesixtygiving.org/category/news/page/2/
- [x] www.charitycommission.gov.uk/ - http://www.threesixtygiving.org/standard/identifiers/
- [x] /support/ - http://www.threesixtygiving.org/standard/identifiers/
- [x] /tools/ - http://www.threesixtygiving.org/standard/reference/

**Comment by stevieflow** [comment]
is there a wordpress plug-in we could use to rerun this?

**Comment by caprenter** [comment]
Use Linkchecker - available from your ubuntu repo I think:
https://wummel.github.io/linkchecker/

**Comment by stevieflow** [comment]
Thanks

http://slashopen.net/ seems to be dead (linked to from http://www.threesixtygiving.org/get-involved/publish-your-data/)  Ill create a new issue on this

**Comment by ekoner** [comment]
@caprenter & @idlemoor please review this plug-in https://wordpress.org/plugins/broken-link-checker/ on the staging site which can email notifications.

**Comment by caprenter** [comment]
The reviews of that plugin don't me great confidence. Additional plugins also means additional overhead in maintaining the site, so I'm keen to avoid adding more.
Linkchecker does the job, although it won't check things unless we run it. I don't think this is really a massive issue for this site.

Closing this as broken links are fixed
