### ISSUE TITLE
What to do with docs.threesixty.org

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#38]
This will also be live at launch. If we kill it we will need to set up some re-directs

**Comment by stevieflow** [comment]
It looks dead now - linked to archiving of https://github.com/ThreeSixtyGiving/threesixtygiving.github.io/issues/9 - not sure whether we should keep this open, or repost in https://github.com/ThreeSixtyGiving/threesixtygiving.github.io/ @caprenter

**Comment by caprenter** [comment]
I think we can close this
