### ISSUE TITLE
Pages that need content fixes

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#39]
- [x]  http://opendataservic.staging.wpengine.com/get-involved/

**Comment by timgdavies** [comment]
I've just been editing this on staging and I think its at a stage that could go live.

However, boxes not displaying quite right - so a layout / css tweak needed: perhaps when responsive issues being covered. 

![screen shot 2015-07-15 at 18 12 24](https://cloud.githubusercontent.com/assets/342624/8704760/1164ede0-2b1d-11e5-9e36-d55fed7dd6f5.png)

**Comment by caprenter** [comment]
I think this is fixed. It depends on your screen size and zoom levels etc, so not much more to be done
