### ISSUE TITLE
Headings don't match navigation

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#42]
from @stevieflow 

http://opendataservic.staging.wpengine.com/get-involved/

I dont like the fact that the headings don't match the navigation :
- Share Your Data -- the link is then labelled Publish Data.  Don't make me think!

**Comment by caprenter** [comment]
Someone needs to work out the policy on this and negotiate a solution, so assigning Steven to that task

**Comment by stevieflow** [comment]
@timgdavies have you an opinion on this?

**Comment by timgdavies** [comment]
In this instance, I suggest 'Publish Data' as the canonical phrase, with the softer words about sharing kept in the paragraph of text.

So: change left-hand section heading to 'Publish data'

**Comment by stevieflow** [comment]
ok - have done so, thanks: http://www.threesixtygiving.org/get-involved/
