### ISSUE TITLE
Links in text

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#43]
from @stevieflow 

http://opendataservic.staging.wpengine.com/about/past-present-and-future/
There could be inline links to The Team and The Company within the text

http://opendataservic.staging.wpengine.com/about/faq/
Eventually - would be good to link to the data on these grants!

**Comment by caprenter** [comment]
@stevieflow - You should have a login to the new site. You can reset password in usual way if not.
Then you can make these changes

**Comment by stevieflow** [comment]
Done, where relevant

Have also added a link to Contact in the last sentence on: http://www.threesixtygiving.org/standard/
