### ISSUE TITLE
Blog Categories

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#44]
from @stevieflow 
Looks as if all posts are categorized?
If we were to categorize them, would there be "room" for a side bar, etc? 
-- maybe a list of recent posts/categories can sit in the footer instead?

**Comment by caprenter** [comment]
I think part of the design was trying to avoid sidebars, but you might take this up with other people to see.

**Comment by stevieflow** [comment]
For now, I've just renamed the Uncategorized category to News & Updates - eg: http://www.threesixtygiving.org/category/news/

There is only one category for all blog posts
