### ISSUE TITLE
Front Page Logos

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#46]
Are we done with Front Page logos?

Currently, they display in a random order;
Are pulled from DKAN via associated datasets (so publishers without data don't get pulled);
There is no limit on how many will be shown;
The size and quality is not great;

....

**Comment by stevieflow** [comment]
I think so - in terms of the mechanisms.  We might want to review this in the future, but the current process is documented on https://github.com/ThreeSixtyGiving/website/blob/master/README.rst - but I added some of the info from this ticket
