### ISSUE TITLE
Use Sentry

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#47]
We could be monitoring this with Sentry

**Comment by stevieflow** [comment]
@idlemoor ?

**Comment by ekoner** [comment]
Pinging @idlemoor & @Bjwebb to confirm or deny

**Comment by Bjwebb** [comment]
This is low priority.

**Comment by morchickit** [comment]
Can I close this one?

**Comment by Bjwebb** [comment]
Closing this as it isn't going to happen, and WPengine is doing what we need.
