### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#48]
On this page:
http://www.threesixtygiving.org/standard/reference/

The CoVE (Convert, Validate and Explore) can be used to round-trip data between these formats, providing structured data for developers, and spreadsheet simplicity if you want to browse, sort and filter data on your desktop.

Links 'CoVE' to http://cove.threesixtygiving.org/ which does not exist.

@timgdavies 
I'm guessing this should be http://cove.opendataservices.coop/360/ - or should it?

**Comment by caprenter** [comment]
This page also has links to 'old' documentation URLS that re-driect to the home page - which isn't right.

E.g. The Organisation Identifier Standard guidance explains how to create this ID, based either on the known company or charity number, or upon identifiers held in the grant-maker's internal systems.
http://docs.threesixtygiving.org/identifiers/#organisation-identifier

**Comment by timgdavies** [comment]
I've just updated the schema and docs pages to address this. Might need pulling into live site manually?

**Comment by caprenter** [comment]
Great - yes - let me check my notes on deployment...

Thanks

**Comment by caprenter** [comment]
Checking the links within the documentation, we now have things like:
http://www.threesixtygiving.org/standard/identifiers/#grant-identifier

but in order to get to that #grant-identifier
the link would be:
http://www.threesixtygiving.org/standard/identifiers/#toc1

I'm not sure where we would change this off the top of my head - either the link, or the target.

I've got trouble deploying the submodule updates, so can't show this on staging at the moment.

**Comment by timgdavies** [comment]
Just been looking at the TOC plugin and noticed:

(a) The javascript is still being called [in the source files here](https://github.com/ThreeSixtyGiving/standard/edit/master/documentation/reference.md) where it shouldn't be. I'll remove that.

(b) If you update the javascript in the theme to:

``` javascript
 jQuery('#toc').toc({
        'selectors': 'h2,h3,h4', //elements to use as headings
        'smoothScrolling': true, //enable or disable smooth scrolling on click
        'prefix': 'toc' //prefix for anchor tags and class names
    });
```

then the headings will become `#toc-grant-identifier` etc. which is more robust to the addition/removal of sections from the page (i.e. new subheadings won't break these links). 

I'll change the source files if you are alright to make those changes to the Wordpress themes...

**Comment by caprenter** [comment]
The code to change in the theme is here: https://github.com/ThreeSixtyGiving/website/blob/master/wp-content/themes/responsive-child/footer.php#L98

..which looks pretty similar - would you please double check your suggested edit?

**Comment by timgdavies** [comment]
Yes - my suggestion is to switch from the code in the theme at https://github.com/ThreeSixtyGiving/website/blob/master/wp-content/themes/responsive-child/footer.php#L98 to use the code above.

A lot of the current code at https://github.com/ThreeSixtyGiving/website/blob/master/wp-content/themes/responsive-child/footer.php#L98 is just repeating defaults from toc.js so is redundant. 

I've tested on a static version of the page (Save As... & editing locally) and it seems to work.

**Comment by caprenter** [comment]
ok -thanks. 

I now have the change locally, and I see you have made updates to the standard repo, so I will pull them locally and test.

Thanks

**Comment by caprenter** [comment]
This should now be fixed on the live site
