### ISSUE TITLE
.com redirect not working properly

### ISSUE THREAD

**Issue by timgdavies** [ThreeSixtyGiving/website#49]
I think this is to do with the current set-up of these domains with Wordpress.com.

We should consider moving the domains to another registrar so that they are easier to manage in future.

**Comment by caprenter** [comment]
whois info says that this is registered with 1and1 but that the nameservers are at wordpress, but I am unable to ping it.

**Comment by caprenter** [comment]
This seems to redirect now. I'm not sure what has changed tho.
