### ISSUE TITLE
Documentation - sentance missing?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#50]
Comparing:
http://www.threesixtygiving.org/standard/identifiers/

with 
https://github.com/ThreeSixtyGiving/standard/blob/master/documentation/identifiers.md

On the website, the following sentence seems to be cut short:

> If you do not have any external registration numbers for the organisation, use your 360 Giving prefix and .

**Comment by timgdavies** [comment]
In the source there is a tooltip for this sentence - but it looks like it is being cut out by the markdown processor. It might be due to the use of quotes within the tooltip.

Assigning caprenter who might be able to  test/explore by editing the file on the staging server manually?

**Comment by caprenter** [comment]
This is a css issue. 
.post-entry span {
  height: 90px; 
  margin-top: -90px; 
  display: block; 
  visibility: hidden; 
}
Should be able to fix it.

**Comment by caprenter** [comment]
This should be fixed now. Please let me know if not. You may need to refresh your browser
