### ISSUE TITLE
(CSV versions also available)

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#53]
The link to (CSV versions also available) from http://www.threesixtygiving.org/standard/

takes people directly to the github repository with very little other information (which should I use? What are these?)

A README in that directory might help, but also I came across this when trying to create a direct download link for CoVE. The CSV link here: http://cove.opendataservices.coop/360/ might need to be reviewed

**Comment by timgdavies** [comment]
This will require a look at the scripts that generate those template files.

Can I assign this to you @caprenter to have a look at writing an initial Readme? 

I've just been playing with similar CSV templates for OCDS at https://github.com/open-contracting/sample-data/tree/master/flat-template and realising we do need more worked through examples, documentation and testing of how the CSV versions should work.

There is also a link here to the issue of Data Package support for CoVE (https://github.com/OpenDataServices/cove/issues/64)

**Comment by ekoner** [comment]
@caprenter is this deployed? Can we close?

**Comment by morchickit** [comment]
@caprenter - ping again :-)
