### ISSUE TITLE
What happens if DKAN is unavailable

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#54]
There is code that regularly calls the DKAN api, and then overwrites files etc.

We need to check what happens if DKAN is unavailable

**Comment by stevieflow** [comment]
@caprenter candidate to close this, as we dont need to pay attention to the issue ongoing?

**Comment by caprenter** [comment]
Yep - as the website no-longer relies on the DKAN instance this is no longer an issue
