### ISSUE TITLE
Broken links JSON Schema page

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#56]
http://www.threesixtygiving.org/standard/reference/#toc-json-schema

The (360Giving Grant identifier guidance) link in the iframe loads within the iframe.

The link to 'full screen' goes to http://wp-content/plugins/threesixty_docs/docson/index.html#/wp-content/plugins/threesixty_docs/standard/schema/360-giving-schema.json

**Comment by caprenter** [comment]
I've had a quick look at these and not sure about how to fix. I can see the use of relative paths might not be working as expected. Hard coding could be an answer.

I'm not sure relying on resources at wp-content/... is a great idea. In this case GitHub is the single source of truth and that could possibly used instead (how?) (although granted, the code used in the current website should be a clone of this repo at the correct commit on the correct branch)

**Comment by caprenter** [comment]
I've taken another look at this today, and it seems that this is partly because a link is hardcoded into the Schema, and the fact that the docson widget loads the schema into the div on the page. As there are other links in the schema that need to work with the div, we can't try to put a _parent condition on the frame or link itself, so this is a case of won't fix I think.

It's a minor issue. Inconvenient if people do come across it, but the information is still shown and can be found elsewhere.

**Comment by ekoner** [comment]
@caprenter please confirm if this can be closed.

**Comment by morchickit** [comment]
@caprenter - ping?

**Comment by caprenter** [comment]
Yeah, with the move to the new documentation site this should no longer be a problem. It was marked as won't fix anyway.
