### ISSUE TITLE
Credit for icons

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#58]
@timgdavies are the icons used on http://www.threesixtygiving.org/standard/ from a source (noun project?)?

We should credit these

I was also looking at icons for https://github.com/ThreeSixtyGiving/website/issues/45 - so might be useful to have them from the same source

**Comment by timgdavies** [comment]
I'm afraid I've not kept track of sources for these, so I would suggest if you are finding icons for #45 you see about replacements for these, and use and credit a consistent set.

**Comment by ekoner** [comment]
The JSON icon here: http://1.1.1.5/bmi/www.threesixtygiving.org/wp-content/uploads/2015/07/json-150x150.png can be credited to https://thenounproject.com/term/json-file/45730/ under creative commons 3. Allocating this update to @caprenter 

NB: Couldn't definitively location the spreadsheet icon: http://www.threesixtygiving.org/wp-content/uploads/2015/07/spreadsheet-150x150.png which may be an altered version of https://thumbsplus.tutsplus.com/uploads/users/23/posts/21996/preview_image/spreadsheet.png?height=300&width=300

**Comment by caprenter** [comment]
I've replaced the spreadsheet icon with a noun project icon and credit both icons: http://www.threesixtygiving.org/standard/
