### ISSUE TITLE
Use Group name for Org in data table

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#59]
On: http://www.threesixtygiving.org/get-involved/data/ - the column "Organisation" doesnt seem to be using the Organisation name, but the name of the dataset.

Example:

http://data.threesixtygiving.org/group/nominet-trust

Group name is "Nominet Trust"
Dataset name is "Nominet Trust Grants"
File name is: "Nominet Trust Grants Data"

In the table on http://www.threesixtygiving.org/get-involved/data/ we have:

Org Name = Nominet Trust Grants
The Data column then seems to use the Dataset and File names accordingly

Can the Organisation column use the Group name?

**Comment by caprenter** [comment]
I've had a look at the code, and the website and the data returned from the API.

We are using the group->display_name from the API
https://github.com/ThreeSixtyGiving/website/blob/master/wp-content/themes/responsive-child/page-data.php#L117
so this could be a bug in the DKAN API, or a misunderstanding of the terms group and organisation etc.

There may be other ways to get the correct the data through other API calls.

It may also be that there are more things that need to be done on this page. I think it's worth reviewing and collecting all tasks together.

**Comment by caprenter** [comment]
This can be reviewed when https://github.com/ThreeSixtyGiving/website/issues/64 is implemented

**Comment by caprenter** [comment]
This is fixed
