### ISSUE TITLE
Public Domain Certification licence is now retired

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#60]
https://creativecommons.org/licenses/publicdomain/

This is linked to from the How to Publish page : http://www.threesixtygiving.org/get-involved/publish-your-data/

**Comment by timgdavies** [comment]
For our purposes this can be replaced with the CC0 Public Domain Dedication: https://creativecommons.org/publicdomain/zero/1.0/

From the CC website, the reason that Public Domain _license_ was retired was "US-specific; co-mingled two very different use cases. Replaced by two separate tools: the CC0 Public Domain Dedication and the Public Domain Mark."

I believe that particular page is managed via Wordpress, so @stevieflow can you make the edit.

Should check we don't mention the license anywhere else.

**Comment by stevieflow** [comment]
No problem - have done the edit.  Thanks @timgdavies
