### ISSUE TITLE
Documentation - extending the summary table - unclear?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#61]
http://www.threesixtygiving.org/standard/reference/#toc-extending-the-summary-table

> Concatenate the relationship and property titles using :

I can see that the subject here is the `:` character, but this can also be read as using a colon to lead into a list of bullet points, potentially.  

Do we need specific markup on the `:` ?

**Comment by practicalparticipation** [comment]
Yes. I suggest wrapping : in pre tags and checking our css formats that in
a code like way.

``` :```
On 15 Sep 2015 11:01, "Steven Flower" <notifications@github.com> wrote:

>
> http://www.threesixtygiving.org/standard/reference/#toc-extending-the-summary-table
>
> Concatenate the relationship and property titles using :
>
> I can see that the subject here is the : character, but this can also be
> read as using a colon to lead into a list of bullet points, potentially.
>
> Do we need specific markup on the : ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThreeSixtyGiving/website/issues/61>.
>
```

**Comment by stevieflow** [comment]
OK - have created a PR: https://github.com/ThreeSixtyGiving/standard/pull/72

Assigning over to @caprenter

**Comment by caprenter** [comment]
This has been merged and will be deployed to the live website the next time we do this
