### ISSUE TITLE
Create example / reference file

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#62]
It would be useful to create and make available a file that is populated with grants from example-org - which people can download and take a look through

**Comment by morchickit** [comment]
@ekoner  - status here?

**Comment by ekoner** [comment]
@morchickit we progressed this internally, I'll ping this over to @stevieflow to confirm.

**Comment by stevieflow** [comment]
We created a whole repository: https://github.com/ThreeSixtyGiving/sample-data - is that the place for subsequent issues, such as https://github.com/ThreeSixtyGiving/sample-data/issues/1 ?

If so, then we should close this

**Comment by ekoner** [comment]
Agreed - closing. @morchickit please review the repo: https://github.com/ThreeSixtyGiving/sample-data and add comments or requests there.

**Comment by morchickit** [comment]
Thanks! Looks good
