### ISSUE TITLE
Publishing codelist(s) on the site

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#66]
We have one codelist - https://github.com/ThreeSixtyGiving/standard/blob/master/codelists/geoCodeType.csv

pointed to from:

http://www.threesixtygiving.org/standard/reference/#toc-location

Just noting - we may want to "publish" this within the actual site

**Comment by caprenter** [comment]
There are other codes which are included in the JSON schema.
Country Codes
Currency Codes
and 
Organisational Types

**Comment by ekoner** [comment]
@stevieflow & @caprenter can you outline how this can be done and an idea of how much work it is? I can then evaluate the priority.

**Comment by morchickit** [comment]
@stevieflow  - is this still relevant now that we are moving the documentation?

**Comment by stevieflow** [comment]
This is still relevant

The decision is whether 360 would like to (re) publish the codes from these lists, or be happy to just point people to them.  The latter is not much work (maybe reviewing the description text in the schema).  The former is much more (working out how to pull in the lists / checking licences / updates etc)

Here's the currency example

> The currency used in amounts. Use the three-letter currency code from ISO 4217 eg: Use GBP for Pounds Sterling.

The link is to https://en.wikipedia.org/wiki/ISO_4217

Perhaps the task is to find reference to each external codelist and then review the link/description text (which is not the focus of the original post)

**Comment by drkane** [comment]
Standard documentation now contains section on codelists: https://standard.threesixtygiving.org/en/latest/technical/codelists/#
