### ISSUE TITLE
(CSV versions also available)

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#68]
On http://www.threesixtygiving.org/standard/ - we might want to rethink how we provide access to CSV versions

We may want to provide "download" access to these file(s) - although not sure how we do so out of GitHub

**Comment by caprenter** [comment]
This is pretty much a duplicate of https://github.com/ThreeSixtyGiving/website/issues/53 - would you see if your concerns are covered there, update that issue if not and close this one please?

**Comment by stevieflow** [comment]
Ah brilliant - thanks @caprenter
