### ISSUE TITLE
Footer font size

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#69]
The footer blocks for the links and blurb seem to be "overly large", or could do with more styling.  Have we any control over these @caprenter ?

![footer](https://cloud.githubusercontent.com/assets/1209944/12813399/a8df36e6-cb2f-11e5-8f08-65d7e4358c15.png)

**Comment by caprenter** [comment]
This is being addressed on the staging site

**Comment by caprenter** [comment]
A new footer is now in place
