### ISSUE TITLE
The standard way of referring to 360Giving is always 360Giving.

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#7]
"NB The standard way of referring to 360Giving is always 360Giving." is from one of the google docs.

The top right image on the new site is of the words

ThreeSixtyGiving

Should it be?

**Comment by timgdavies** [comment]
Just checking with Alice - but I think that a switch to 360GIVING in the header would be correct - which would move us to two-tones of grey, rather than the three currently used.

**Comment by timgdavies** [comment]
Change confirmed.

**Comment by timgdavies** [comment]
Change required to 360Giving  in the header.

**Comment by caprenter** [comment]
@timgdavies Currently the header uses an image to:
a) Get the thicker font
b) Get the shading

If we want this in the same style, I think this is a job for Claudio.
If it's a job for Claudio it needs to be clearly specced -(is it all Uppercase or not?)

**Comment by timgdavies** [comment]
Is there any way we can do this with CSS?

**Comment by caprenter** [comment]
Not that I know of

**Comment by timgdavies** [comment]
ok. Can you ask Claudio for the updated graphic then.

**Comment by caprenter** [comment]
Email sent

**Comment by caprenter** [comment]
This has been replaced
