### ISSUE TITLE
The 360 Bridge tool...

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#71]
From http://www.threesixtygiving.org/standard/reference/
"The 360 Bridge tool supports round-tripping of data between Summary spreadsheet, multi-table datapackage and JSON representations."

I'm not sure if this still exists. The link is a 404, and I'm guessing this is now CoVE - but we don't have a 360 specific deployment of cove (do we want one is another question)

**Comment by caprenter** [comment]
See also: https://github.com/ThreeSixtyGiving/standard/issues/100

**Comment by timgdavies** [comment]
This is CoVE.

Documentation should be updated accordingly pointing to CoVE/360 version. No need to a specific deployment at this stage.

**Comment by stevieflow** [comment]
NB - this are two links 

> The 360 Bridge tool uses these properties when creating templates. However, it is possible, following the same naming convention for fields, to bring most properties into the Activity table if a particular use-case requires.
