### ISSUE TITLE
Slashopen is not live

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#73]
At http://www.threesixtygiving.org/get-involved/publish-your-data/ there is a link to http://slashopen.net/

Propose we remove reliance on this external service by changing text to (replacing /open with dedicated):

> We recommend creating dedicated page on your site where you can list your data for download, but you can host the data anywhere on your site and link to it where it can be easily found. For example, link to your data file of grants alongside your annual report.

@practicalparticipation agree?

(part of https://github.com/ThreeSixtyGiving/website/issues/35)

**Comment by timgdavies** [comment]
I would suggest we still encourage (but not require) use of /open as the page location.

**Comment by stevieflow** [comment]
OK - so 

> We recommend creating dedicated page on your site where you can list your data for download.  This could be at a dedicated "/open" section/page on your site, to provide more information to people.  However, you can host the data anywhere on your site and link to it where it can be easily found. For example, linking to your data file of grants alongside your annual report.

**Comment by caprenter** [comment]
This can be altered directly via the wordpress pages

**Comment by stevieflow** [comment]
OK thanks @caprenter - have done so: http://www.threesixtygiving.org/get-involved/publish-your-data/
