### ISSUE TITLE
Broken internal link

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#74]
On http://www.threesixtygiving.org/standard/identifiers/

The sentence:

> For organisation identifiers, follow the organisation identifier guidance below which is designed to support links to be made between 360Giving, and other datasets about an organisation

The link to org identifiers goes to

http://www.threesixtygiving.org/standard/identifiers/#organisation-identifier

this doesnt seem to work.  The link seems to be:

http://www.threesixtygiving.org/standard/identifiers/#toc-organisation-identifier

**Comment by caprenter** [comment]
This is not as straight forward as it first appears.

All the links on the left hand side of this page are generated by javascript (if you don't have javascript you don't see any navigation at all.) This is based on the (h) heading html tags in the page. (The javascript adds in the anchors and names them).

The html heading tags are generated from the original markdown documents, but it doesn't create the necessary anchor tags. The Parsedown php library that we use seems not to want to do this.

So the 'toc-' prefix is implementation specific (to us) -  whereas the link used in the markdown is fairly standard across the board. Making our stuff respect the correct markdown is really the way to fix this, but does not seem to be simple.

Short term options are:
- Remove the link - there is other navigation and it does say 'below'
- Break the documentation, to make the website work

**Comment by morchickit** [comment]
@stevieflow - should I close it since we will fix it with the new documentation?

**Comment by stevieflow** [comment]
Eventually.  Let's leave it to check when we have the new docs though
