### ISSUE TITLE
Nav Menu on document pages

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#8]
Final decisions need to made on the format of this additional nav bar.
see e.g. http://opendataservic.staging.wpengine.com/standard/publish/
- [ ] Debugging needs to happen on how h3, h4 items are picked up
- [x] Position of bar needs fixing. Currently fixed at 60px, but this leaves a gap on scroll
- [ ] Potentially will run off the screen if too many items and impossible to scroll down

**Comment by timgdavies** [comment]
Good stuff. 

Would fixing the top bar on all pages (so menu is always visible, and page scrolls beneath it) make sense?

**Comment by caprenter** [comment]
Fixed nav bar fixes 'Position of bar needs fixing'. There are still other issues here

**Comment by caprenter** [comment]
I think this is done. @timgdavies can we close this?
