### ISSUE TITLE
Include licence info in 360 dataset listing

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/website#85]
On the dataset listing (http://www.threesixtygiving.org/get-involved/data/) , we should include the name of the licence, and a link to it (if available)

Related to https://github.com/ThreeSixtyGiving/website/issues/64

This data should be in Salesforce CRM - but needs checking -- > @ekoner

**Comment by caprenter** [comment]
You can see what we can do right now with this info here:
http://opendataservic.staging.wpengine.com/get-involved/data/

**Comment by stevieflow** [comment]
Fantastic, thanks @caprenter 

So 
- how do we turn that link into a link?
- and, how can we provide text for the link (as in the name of the licence?)?

(In Saleforice, there seems to be a lookup/table to select from - but the link and label do not seem to make it out in the JSON)

**Comment by caprenter** [comment]
It's easy enough to use that URL to make it into a link.

In terms of getting the name of the licence I need to check with @timgdavies  about 
1) Whether we can alter the output of the saleseforce to include the name, and not interfere with the dcat standard that we are trying to copy.
2) If we can't do that, we need to create a mapping in the website code of URLs and names that we can look up against - this is just a bit of a pain in terms of keeping in synch. I guess a third option would be to create another feed out of salesforce with the mapping in it.

**Comment by stevieflow** [comment]
This page doesnt include the licence any more: http://opendataservic.staging.wpengine.com/get-involved/data/

**Comment by caprenter** [comment]
Staging sites are subject to change

**Comment by caprenter** [comment]
And it's back: http://opendataservic.staging.wpengine.com/data/find-data/

**Comment by caprenter** [comment]
This is done and live, so closing
