### ISSUE TITLE
GrantNav page

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#89]
@idlemoor is waiting to do redirect from the Grant Nav domain to a page on the website (blog post by @stevieflow ?)

**Comment by ekoner** [comment]
A page has been set up here: http://www.threesixtygiving.org/grantnav/ - allocated to @idlemoor

**Comment by caprenter** [comment]
@idlemoor - my understanding is that this is done - can you confirm and close pls?

**Comment by idlemoor** [comment]
Yes it was done, see https://opendataservices.plan.io/issues/4785 ... didn't spot this github issue :(
