### ISSUE TITLE
Fix standard documentation

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#9]
Single source of truth for documentation pages needs review:

In partucluar:
- [ ] Images are missing
- [ ] Some other data is not parsing: e.g. Field definitions {% for field in site.data.360-summary-table-schema.fields %} {% endfor %}
- [ ] JSON schema is missing: http://opendataservic.staging.wpengine.com/standard/reference/#toc5

**Comment by caprenter** [comment]
@timgdavies might be worth you checking these issues out to see if there are simple fixes

**Comment by timgdavies** [comment]
Ok. I'll look at this by end of Monday.

**Comment by caprenter** [comment]
Where are we at with this? @timgdavies I think it is done? Can we close this and then open any new issues as bugs?

**Comment by practicalparticipation** [comment]
Agreed.
