### ISSUE TITLE
The Reference page doesn't mention CSV format

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/website#95]
The Reference page doesn't mention CSV format under Spreadsheet but we bring it in for our Resources and reference it on GitHub. Worth amending so they look the same?

**Comment by ekoner** [comment]
+1 to make them look the same. @caprenter happy to take this on?

**Comment by morchickit** [comment]
this is fixed, isn't it @ekoner ?

**Comment by ekoner** [comment]
No, it mentions Spreadsheet (Excel) and JSON, so still needs doing @caprenter

**Comment by caprenter** [comment]
Yup

**Comment by ekoner** [comment]
Apologies, it does mention CSV **under** the Spreadsheet format. So I'm closing this:

> Spreadsheet Template (Excel), with user-friendly column headings, summary sheet and tabs for additional information.
> (CSV versions also available.)
